[package]
name = "nofus"
version = "0.1.0"
edition = "2021"
authors = ["Hunter Horsman <kariudo@gmail.com>"]

[dependencies]
clap = { version = "4.5.31", features = ["derive"] }
inotify = "0.11"
proc-mounts = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_yml = "0.0.12"
