[package]
name = "nofus"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.31", features = ["derive"] }
inotify = "0.10"
proc-mounts = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
